### ISSUE TITLE
Is it possible to detect the calendar has been changed by using gesture 

### ISSUE THREAD

**Issue by EragonJ** [GGJJack/SwiftUICalendar#2]
The Calendar Scroll example is buttons, so you can use buttons to switch the calendar view and then trigger actions to update information on the calendar.

https://github.com/GGJJack/SwiftUICalendar#calendar-scroll

But in this case, if the user tries to swipe the calendar, there is no way to detect this gesture and do related actions. Is there any way to achieve this? Thank you!

**Comment by GGJJack** [comment]
The calendar controller has yearMonth as Published.

If you want to detect changes in UI, you can try onChange.

```Swift
CalendarView(controller) { date in
 ....
}
.onChange(of: controller.yearMonth) { yearMonth in
    print(yearMonth)
}
```

Or if you have AnyCancellable Set you can try this.

```Swift
var subscriptions = Set<AnyCancellable>()
controller.$yearMonth.sink { yearMonth in
    print(yearMonth)
}
.store(in: &subscriptions)
```

**Comment by EragonJ** [comment]
Thanks for the answer! Thank you :)
